services:
  - type: web
    name: nttdata-hr-assistant
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 3000


